# Generated by Django 5.1 on 2025-03-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
