# Generated by Django 5.1 on 2025-02-18 19:23

import AcadME4_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0002_customuser_user_type_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignments/', validators=[AcadME4_app.models.validate_pdf])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcadME4_app.staffs')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcadME4_app.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_file', models.FileField(upload_to='submissions/', validators=[AcadME4_app.models.validate_pdf])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Graded', 'Graded'), ('Late', 'Late')], default='Submitted', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('marks_obtained', models.FloatField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcadME4_app.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcadME4_app.students')),
            ],
        ),
    ]
