# Generated by Django 5.1.6 on 2025-02-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0003_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_assignment_marks',
            new_name='assignment1_marks',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_exam_marks',
            new_name='assignment2_marks',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='periodical1_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='periodical2_marks',
            field=models.FloatField(default=0),
        ),
    ]
