# Generated by Django 5.1.6 on 2025-02-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0004_rename_subject_assignment_marks_studentresult_assignment1_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='assignment1_marks',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='assignment2_marks',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='periodical1_marks',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='periodical2_marks',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
