# Generated by Django 5.1.6 on 2025-02-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0006_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
