# Generated by Django 5.1 on 2025-02-25 19:54

import AcadME4_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AcadME4_app", "0008_timetable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to="syllabus/",
                        validators=[AcadME4_app.models.validate_pdf],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AcadME4_app.subjects",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AcadME4_app.staffs",
                    ),
                ),
            ],
        ),
    ]
