# Generated by Django 5.1 on 2025-03-30 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0009_alter_assignmentsubmission_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='marks_obtained',
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcadME4_app.students'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_submission'),
        ),
    ]
