# Generated by Django 5.1 on 2025-03-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0010_remove_assignmentsubmission_marks_obtained_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignmentsubmission',
            name='unique_assignment_submission',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks_obtained',
            field=models.FloatField(default=0),
        ),
    ]
