# Generated by Django 5.1 on 2025-02-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0010_branch_students_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AcadME4_app.courses'),
        ),
    ]
