# Generated by Django 5.1 on 2025-02-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0011_branch_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='branch',
            new_name='branch_id',
        ),
    ]
