# Generated by Django 5.1 on 2025-03-01 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0012_rename_branch_students_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='branch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='AcadME4_app.branch'),
        ),
    ]
