# Generated by Django 5.1.6 on 2025-03-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0013_subjects_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_id', models.CharField(max_length=50, unique=True)),
                ('lab_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcadME4_app.subjects')),
            ],
        ),
    ]
