# Generated by Django 5.1.6 on 2025-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0014_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='has_lab',
            field=models.BooleanField(default=False),
        ),
    ]
