# Generated by Django 5.1.6 on 2025-03-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0015_subjects_has_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='has_lab',
        ),
    ]
