# Generated by Django 5.1.6 on 2025-03-01 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0017_subjects_has_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AcadME4_app.labs'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AcadME4_app.subjects'),
        ),
    ]
