# Generated by Django 5.1.6 on 2025-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0018_timetable_lab_alter_timetable_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], default='theory', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='class_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], default='theory', max_length=10),
        ),
    ]
