# Generated by Django 5.1.6 on 2025-03-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcadME4_app', '0019_attendance_class_type_attendancereport_class_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='lab',
        ),
    ]
